# --- Site settings ---
title: Ricardo Mirville
tagline: Data Science & Analytics
description: SQL • Python • Power BI
url: "https://ricardobmirville.github.io"
baseurl: "/Portfolio"    # "" if this is your user site repo

# --- Use Hyde (remote theme) ---
remote_theme: poole/hyde

# GitHub Pages-allowed plugins
plugins:
  - jekyll-remote-theme

# Sidebar (Hyde picks up title/description automatically)
author:
  name: Ricardo Mirville
  email: Ricardo.Mirville@gmail.com
  github: RicardoBMirville
  linkedin: ricardo-mirville-28474413a
  # add more keys if you want; we’ll surface via the About/Projects pages

# Optional: add your résumé link for easy reuse
resume_path: "/assets/Ricardo_Mirville_Resume_2025.pdf"

# Load a small custom stylesheet (optional)
# Hyde includes its own styles; you can override below
sass:
  style: compressed

# Add a plain CSS file too (for tiny overrides)
defaults:
  - scope:
      path: ""
    values:
      layout: page

# If you want Hyde’s blog-style dates on posts only:
# defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: post