############################
# --- Required options --- #
############################

layout: page
title: Ricardo Mirville — Portfolio
author: Ricardo Mirville
permalink: /

###############################################
# --- List of links in the navigation bar --- #
###############################################

# ---- site/base paths ----
url: "https://ricardobmirville.github.io"
baseurl: "/Portfolio"        

# ---- navbar ----
navbar-links:
  About: "about"
  Projects: "projects"
  Resume: "{{ '/assets/Ricardo_Mirville_Resume_2025.pdf' | relative_url }}"
  Contact: "contact"

  <div class="row align-items-start g-4">

  <!-- LEFT: name + photo + quick actions -->
  <aside class="col-lg-4 sidebar-sticky">
    <img src="{{ '/assets/img/ricardo.jpg' | relative_url }}" alt="Ricardo Mirville" class="img-fluid img-avatar mb-3" width="240" height="240">
    <h1 class="h3 h-compact">Ricardo Mirville</h1>
    <p class="text-muted h-compact">Data Science & Analytics — SQL • Python • Power BI</p>

    <div class="d-grid gap-2 mt-3">
      <a class="btn btn-primary" href="{{ '/assets/Ricardo_Mirville_Resume_2025.pdf' | relative_url }}">View résumé</a>
      <a class="btn btn-outline-secondary" href="{{ '/contact' | relative_url }}">Contact</a>
      <a class="btn btn-outline-primary" href="{{ '/projects' | relative_url }}">See projects</a>
    </div>
  </aside>

  <!-- RIGHT: intro + highlights -->
  <section class="col-lg-8">
    <p>I help teams turn raw data into clear, decision-ready insights — building clean datasets, thoughtful visuals, and practical models.</p>

    <h2 class="h4 mt-4">What I’m good at</h2>
    <ul>
      <li>SQL &amp; Python for analysis and automation</li>
      <li>Power BI dashboards that tell the story</li>
      <li>Data modeling, validation, and performance tuning (materialized views, indexing)</li>
      <li>Translating stakeholder goals into clean metrics &amp; reproducible work</li>
    </ul>

    <h2 class="h4 mt-4">Recent highlights</h2>
    <ul>
      <li>Streamlined dashboard performance with materialized views, cutting refresh time.</li>
      <li>Built reliable visualizations for web apps across global teams.</li>
      <li>Audited new implementations and fixed tricky data issues before they became incidents.</li>
    </ul>
  </section>
</div>

<hr>


################
# --- Logo --- #
################

avatar: "/assets/img/ricardo.jpg"
round-avatar: true
#title-img:

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "Ricardo.Mirville@gmail.com"
  github: RicardoBMirville
  linkedin: ricardo-mirville-28474413a

rss-description: Portfolio, projects, and case studies from Ricardo Mirville

###########################
# --- General options --- #
###########################

share-links-active:
  twitter: false
  facebook: false
  linkedin: true
  vk: false
  reddit: false

url-pretty: "ricardobmirville.github.io"
title

site-css:
  - "/assets/css/custom.css"
  
