title: Ricardo Mirville — Portfolio
author: Ricardo Mirville

# project site paths
url: "https://ricardobmirville.github.io"
baseurl: "/Portfolio"

# navbar
navbar-links:
  About: "about"
  Projects: "projects"
  Resume: "{{ '/assets/Ricardo_Mirville_Resume_2025.pdf' | relative_url }}"
  Contact: "contact"

# logo (optional)
avatar: "/assets/img/ricardo.jpg"
round-avatar: true

# footer socials
social-network-links:
  email: "Ricardo.Mirville@gmail.com"
  github: RicardoBMirville
  linkedin: ricardo-mirville-28474413a

# load your custom css
site-css:
  - "{{ '/assets/css/custom.css' | relative_url }}"

# jekyll basics (safe for GitHub Pages)
timezone: "America/New_York"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: true
  - scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
