############################
# --- Required options --- #
############################

title: Ricardo Mirville — Portfolio
author: Ricardo Mirville

###############################################
# --- List of links in the navigation bar --- #
###############################################

# ---- site/base paths ----
url: "https://ricardobmirville.github.io"
baseurl: "/Portfolio"        # repo name, with a leading slash

# ---- navbar ----
navbar-links:
  About: "about"
  Projects: "projects"
  Resume: "{{ '/assets/Ricardo_Mirville_Resume_2025.pdf' | relative_url }}"
  Contact: "contact"

################
# --- Logo --- #
################

avatar: "/assets/img/ricardo.jpg"
round-avatar: true
#title-img:

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "Ricardo.Mirville@gmail.com"
  github: RicardoBMirville
  linkedin: ricardo-mirville-28474413a

rss-description: Portfolio, projects, and case studies from Ricardo Mirville

###########################
# --- General options --- #
###########################

share-links-active:
  twitter: false
  facebook: false
  linkedin: true
  vk: false
  reddit: false

url-pretty: "ricardobmirville.github.io"
title
